const NoteBookActionTypes = Object.freeze({
    FETCH_NOTEBOOK_REQUEST: 'NOTEBOOK_FETCH_NOTEBOOK_REQUEST',
    FETCH_NOTEBOOK_SUCCESS: 'NOTEBOOK_FETCH_NOTEBOOK_SUCCESS',
    FETCH_NOTEBOOK_FAILURE: 'NOTEBOOK_FETCH_NOTEBOOK_FAILURE'
});

export default NoteBookActionTypes;