const NoteActionTypes = Object.freeze({
    FETCH_NOTES_REQUEST: 'NOTE_FETCH_NOTES_REQUEST',
    FETCH_NOTES_SUCCESS: 'NOTE_FETCH_NOTES_SUCCESS',
    FETCH_NOTES_FAILURE: 'NOTE_FETCH_NOTES_FAILURE'
});

export default NoteActionTypes;